Targets
BrachaG/MYNYTasks pull request #12
Opened 2023-05-22 10:37 UTC by AyalaTamar

2023-05-28 12:15 UTC, BrachaG requested changes
לא לשכוח להריץ את מסדר הקוד

2023-05-28 12:15 UTC, BrachaG commented on Tasks/Tasks/sqlScripts/statusTable.sql
> +    iStatusId INT PRIMARY KEY NOT NULL,
צריך להיות שדות כמו כל הטבלאות של הטבלאות קוד

2023-05-28 12:15 UTC, BrachaG commented on Tasks/Tasks/sqlScripts/type.sql
> +CREATE TYPE PersonIds AS TABLE(
זה בשביל שיוכלו לשלוח טבלה לפרוצדורה?
נראה לי מורכב אפשר פשוט לשלוח xml

2023-05-31 14:51 UTC, AyalaTamar commented on Tasks/Service/ITargetsService.cs
> +        Task AddTarget(string Comment, int TargetId, int[] PersonId, DateTime? TargetDate);
אין צורך בקבלת הברנצ' כיון ששלפנו אותו אוטומט בפורצדורה

2023-05-31 14:59 UTC, AyalaTamar commented on Tasks/Tasks/sqlScripts/createTargetsTable.sql
> +  iTargetId INT FOREIGN KEY REFERENCES tbl_code_targets(iTargetId) NOT NULL,
יצירת קישור בין TargetId לcodeTypeTarget, זה לא נכון?

2023-05-31 15:51 UTC, AyalaTamar commented on Tasks/Tasks/sqlScripts/type.sql
> +CREATE TYPE PersonIds AS TABLE(
זה עובד טוב ונקי
יש עדיפות לXML?

2023-06-05 08:44 UTC, BrachaG requested changes

2023-06-05 08:44 UTC, BrachaG commented on Tasks/Entities/CodeTable.cs
>      }
כמובן תחזירו את השינויים אחורה...

2023-06-05 08:44 UTC, BrachaG commented on Tasks/Service/ITargetsService.cs
> +    public interface ITargetsService
משתנים בפונקציות **תמיד** מתחיל באות קטנה
רק שמות הפונקציה הם באות גדולה

2023-06-05 08:44 UTC, BrachaG commented on Tasks/Service/TargetsService.cs
> +        ISqlDataAccess _SqlDataAccess;
_sqlDataAccess
s קטנה

2023-06-05 08:44 UTC, BrachaG commented on Tasks/Service/TargetsService.cs
> +        public TargetsService(ISqlDataAccess SqlDataAccess, ILogger<TargetsService> logger, IObjectGenerator<Target> userObjectGenerator)
S קטנה

2023-06-05 08:44 UTC, BrachaG commented on Tasks/Service/TargetsService.cs
> +                _logger.LogError("GetTargetsByUserId ", ex);
ולהחזיר 400 לקליינט

2023-06-05 08:44 UTC, BrachaG commented on Tasks/Service/TargetsService.cs
> +            DataTable personIds = new DataTable();
זה לא נכון לבדוק ככה הרשאות
כלומר אם הוא שלח personId חייב להיות שהוא מנהל?
כי אם רכז ישלח personId????
חייבים לבדוק הרשאות ולא להסתמך על נתונים שמקבלים מהקליינט

2023-06-05 08:44 UTC, BrachaG commented on Tasks/Service/TargetsService.cs
> +            personIds.Columns.Add("Id", typeof(int));
לא הבנתי את הכנ"ל

2023-06-05 08:44 UTC, BrachaG commented on Tasks/Service/TargetsService.cs
> +            {
בכל מקום שעשיתם catch תחזירו 400 לקליינט

2023-06-05 08:44 UTC, BrachaG commented on Tasks/Service/TargetsService.cs
> +        ISqlDataAccess _SqlDataAccess;
כמובן, אשמח שתעברו על כל הקוד שכתבתם ותשנו את שמות המשתנים לאות קטנה

2023-06-05 08:44 UTC, BrachaG commented on Tasks/Tasks/Controllers/TargetsController.cs
> +            if (PersonId == null)
לא בודקים הרשאות לפי משתנים מהקליינט (כפי שכתבתי למעלה..)

2023-06-05 08:44 UTC, BrachaG commented on Tasks/Tasks/Controllers/TargetsController.cs
> +            if (PersonId == null)
וכן בקונטרולר אני לא רוצה שיהיה פונקציונליות חוץ מלשלוף את את היוזר וההרשאות ולהפעיל את הסרביס

2023-06-05 08:44 UTC, BrachaG commented on Tasks/Tasks/sqlScripts/statusTable.sql
> +     iSysRowStatus BIT NOT NULL
תוסיפו גם קוד שממלא את הטבלה בערכים בדיפולטיביים
(יש עוד טבלה כזאת נכון? אם כן תמלאו גם שם...)

2023-06-28 13:28 UTC, BrachaG requested changes

2023-06-28 13:28 UTC, BrachaG commented on Tasks/Service/ITargetsService.cs
> +        Task<ActionResult<string>> AddTarget(string comment, int typeTargetId, int[] personId, int BranchId, DateTime? targetDate, int creatorId,int PermissionLevelId);
PermissionLevelId - צריך להיות באות קטנה!

2023-06-28 13:28 UTC, BrachaG commented on Tasks/Service/PermissionLevelEnum.cs
> +        public enum PermissionLevel { NYmanagar = 1, coordinator = 2, SystemManager = 3 };
לרדת שורה אחרי כל סוג

2023-06-28 13:28 UTC, BrachaG commented on Tasks/Service/PermissionLevelEnum.cs
> +        public enum PermissionLevel { NYmanagar = 1, coordinator = 2, SystemManager = 3 };
זה לא המספרים הנכונים
יש גם את 4 שזה הנהלה
<img width="185" alt="image" src="https://github.com/BrachaG/MYNYTasks/assets/95280647/bbc38f5d-57bf-49e9-adbd-5e3823d3131b">

ו-3 בכלל לא יכולה לעשות לוגין
ומה לגבי רכז?

2023-06-28 13:28 UTC, BrachaG commented on Tasks/Tasks/Controllers/TargetsController.cs
> +            var PermissionLevelId = HttpContext.Items.TryGetValue("PermissionLevelId", out var PermissionLevelIdValue) && PermissionLevelIdValue is int PermissionLevelIdInt ? PermissionLevelIdInt : -
PermissionLevelId - אות קטנה
בבקשה תעברו על הכל ותשנו!

2023-06-28 13:28 UTC, BrachaG commented on Tasks/Tasks/Controllers/TargetsController.cs
> +            int PermissionLevelId = HttpContext.Items.TryGetValue("PermissionLevelId", out var PermissionLevelIdValue) && PermissionLevelIdValue is int PermissionLevelIdInt ? PermissionLevelIdInt : -
אולי במקום לכתוב את כל זה כל קריאה מחדש
אפשר פשוט לעשות את זה בקונטרקטור?

2023-06-28 13:28 UTC, BrachaG commented on Tasks/Tasks/sqlScripts/statusTable.sql
> +     iSysRowStatus BIT NOT NULL
איפה הטיפול בהערה הקודמת?

2023-06-29 12:43 UTC, AyalaTamar commented on Tasks/Service/PermissionLevelEnum.cs
> +        public enum PermissionLevel { NYmanagar = 1, coordinator = 2, SystemManager = 3 };
הרכז שהוא מספר 2
בעצם שאלנו האם הpermissionLevel הוא 2 ואז הוא  מורשה להוסיף יעד רק לעצמו ולא לעוד אנשים-ככה אמרת לנו בזמנו
ולכן כאשר הוא רכז הצבנו באוטומט שהאנשים שלהם הוא מוסיף זה הid של עצמו

2023-06-29 13:38 UTC, AyalaTamar commented on Tasks/Tasks/sqlScripts/statusTable.sql
> +     iSysRowStatus BIT NOT NULL
הוספנו קבצים בתיקייה של הקבצים: Target_Status Data  , tbl_code_Target data
הקוד שבקבצים אלו מכניס את הנתונים לטבלה.

2023-07-02 08:43 UTC, BrachaG requested changes

2023-07-02 08:43 UTC, BrachaG commented on Tasks/Service/PermissionLevelEnum.cs
> +        };
כל זה, זה משתמשי הנהלה
מה עם רכזים?
הם נכנסים?

2023-07-02 08:43 UTC, BrachaG commented on Tasks/Service/PermissionLevelEnum.cs
> +        };
איך בדקתם בכל מקום האם זה רכז?

2023-07-02 08:43 UTC, BrachaG commented on Tasks/Tasks/wwwroot/images/1.png
אפשר למחוק :)

2023-07-02 08:43 UTC, BrachaG commented on Tasks/Tasks/wwwroot/images/3.png
אפשר למחוק  :)

2023-07-02 08:43 UTC, BrachaG commented on Tasks/Service/PermissionLevelEnum.cs
> +        };
בדקתי עכשיו 2 זה רכז
זה הבדיקות שעשיתם בכל מקום במערכת?

מה לגבי הלוגין כתבתם פרוצדורה חדשה?
אני לא רואה קומיט על זה

2023-07-02 09:41 UTC, AyalaTamar commented on Tasks/Service/PermissionLevelEnum.cs
> +        };
עשינו בדיקה האם הוא רכז בהוספת יעד לאנשים בסרבר:
  if (permissionLevelId == (int)PermissionLevelEnum.PermissionLevel.coordinator)
האם לעשות איזשהי ולידציה בפורצדורה של הכנסה אחרי הבדיקה בסרבר?
חוץ מזה בדקנו את ההרשאות גם בשליפת יעד ובהתאם לזאת מה לשלוף
וכמובן בלוגין בדקנו האם רשאי להכנס למערכת-האם ההרשאה היא 1 או 2 או 4
הפורצדורת לוגין  שינינו את השם שלה מהמקור כלומר לא שינינו את הפורצדורה שקיימת
את יכולה לראות שהשם שונה-מתחיל בsu

2023-07-02 10:04 UTC, BrachaG approved these changes

2023-07-02 11:32 UTC, merged