Can activate
BrachaG/MYNYTasks pull request #18
Opened 2023-06-29 11:35 UTC by yaeligrilak

2023-07-23 20:21 UTC, BrachaG requested changes

2023-07-23 20:21 UTC, BrachaG commented on ny-tasks/src/app/app-routing.module.ts
> +    { path: 'targets', component: TargetsComponent },
צריך להוסיף לכל הניווטים

2023-07-23 20:21 UTC, BrachaG commented on ny-tasks/src/app/header/header.component.html
> +    <label>שלום {{userName}},</label><label>{{userPermission === '2' ? 'רכז': 'הנהלה'}}</label>
יש עוד סוג הרשאה של מנהל לא?
נראה לי גם 4 לא?

2023-07-23 20:21 UTC, BrachaG commented on ny-tasks/src/app/header/header.component.ts
> +    this.change=false;
למה צריך את המשתנה change?

2023-07-23 20:21 UTC, BrachaG commented on ny-tasks/src/app/header/header.component.ts
> +    localStorage.removeItem("jwt-token");
צריך לנקוץ את כל ה-local storage
לא רק טוקן

2023-07-23 20:21 UTC, BrachaG commented on ny-tasks/src/app/pages/survey-results/american-question/american-question.component.html
> +<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.7.0"></script>
מה זה הסקריפיטים האלו??

2023-07-23 20:21 UTC, BrachaG commented on ny-tasks/src/app/pages/survey-results/survey-results.component.html
> +            <label class="h4-regular">תמונות משתמשים</label>
זה לא נמצא כבר ב-header?
אין פה כפילות?

2023-07-23 20:21 UTC, BrachaG commented on ny-tasks/src/app/pages/survey-results/survey-results.component.html
> +            <label class="h4-regular">תמונות משתמשים</label>
גם כל ה-checkbox  לא אמרו להיות זה כבר מה-header!

2023-07-23 20:21 UTC, BrachaG commented on ny-tasks/src/app/pages/survey-results/text-question/text-question.component.ts
> +    lQuestions: [],
נקודה למחשה
לא תיקון דחוף
האם לא כדאי שיהיה קומפוננטה בסיסית לסוגי השאלות שכל סוגי השאלות יורשים ממנה
זה אמור לחסוך המון קוד כפול

2023-07-23 20:21 UTC, BrachaG commented on ny-tasks/src/app/pages/survey/survey.component.scss
בכוונה מחקתם את כ ה-css הזה?

2023-07-25 14:51 UTC, yaeligrilak commented on Tasks/Entities/Branch.cs
>          public int iBranchId { get; set; }
למה שיהיה nullable? ה iBranchId?

2023-07-25 14:53 UTC, yaeligrilak commented on Tasks/Entities/Options.cs
> +    {
זה בשביל תשובות אמריקאיות, כמה ענו מכל אופציה בשביל הדיאגרמה

2023-07-25 15:04 UTC, yaeligrilak commented on Tasks/Entities/ResultsForSurvey.cs
> +    {
זה לא טבלה

2023-07-25 17:26 UTC, yaeligrilak commented on Tasks/sql/getBranchesGroups.sql
> +    FROM dbo.tbl_su_Groups G;
ALTER PROCEDURE su_GetBranchesGruops_SLCT
AS
BEGIN
    --SELECT G.iGroupId, G.nvGroupName
    --FROM dbo.tbl_su_Groups G;
    SELECT G.iGroupId, BG.iBranchId, Br.nvBranchName,G.nvGroupName
    FROM dbo.tbl_su_Groups G
    INNER JOIN dbo.tbl_su_BranchesGroups BG ON G.iGroupId = BG.iGroupId
    INNER JOIN dbo.tbl_my_Branches Br ON BG.iBranchId = Br.iBranchId;
END
  try
            {
                DataTable dt = await _sqlDataAccess.ExecuteDatatableSP("su_GetBranchesGruops_SLCT", null);
                List<Branch> branches = _branchObjectGenerator.GeneratListFromDataTable(dt);
                List<BranchGroup> branchGroups = new List<BranchGroup>();
                foreach (DataRow dataRow in dt.Rows)
                {
                    BranchGroup? branchGroup = branchGroups.Find(group => group.iGroupId == int.Parse(dataRow[0]?.ToString()));
                    if (branchGroup == null)
                        branchGroups.Add(new BranchGroup() { iGroupId = int.Parse(dataRow[0]?.ToString()), nvGroupName = dataRow[3]?.ToString(), lBranches = new List<Branch>() });
                }
                foreach (Branch branch in branches)
                {
                    BranchGroup? branchGroup = branchGroups.Find(group => group.iGroupId == branch.iGroupId);
                    if (branchGroup != null)
                        branchGroup.lBranches.Add(branch);
                }
                return branchGroups;
            }
            catch (Exception ex)
            {
                _logger.LogError("Failed to create group", ex);
                return new StatusCodeResult(400);
            }
        }
        
        ככה זה עדיף?

2023-07-25 17:29 UTC, yaeligrilak commented on ny-tasks/src/app/header/header.component.html
> +    <label>שלום {{userName}},</label><label>{{userPermission === '2' ? 'רכז': 'הנהלה'}}</label>
השאלה שם זה אם הוא 2 אז הוא רכז אם לא אז הנהלה, זה התהפך בגלל העברית

2023-07-25 17:38 UTC, yaeligrilak commented on ny-tasks/src/app/pages/survey-results/survey-results.component.html
> +            <label class="h4-regular">תמונות משתמשים</label>
אמרת שלא צריך את זה בכל עמוד רק בתוך תוצאות סקרים

2023-07-25 17:41 UTC, yaeligrilak commented on ny-tasks/src/app/pages/survey/survey.component.scss
כן, זה דברים שהיו כפולים

2023-07-31 07:34 UTC, BrachaG approved these changes

2023-07-31 07:34 UTC, BrachaG commented on ny-tasks/src/app/header/header.component.ts
> +    this.change=false;
אהה זה יכול להישאר ככה עכשיו אבל זה בעיצוב החדש ששלחו לא צריך את זה,
אבל ישנו/תשנו את זה כשתעשו את העיצוב החדש

2023-07-31 07:35 UTC, BrachaG commented on ny-tasks/src/app/pages/survey-results/survey-results.component.html
> +            <label class="h4-regular">תמונות משתמשים</label>
צודקות שכחתי!!
אבל נראה לי ראיתי גם קוד ב-headr שזה נמצא שם אז תמחקו משם

2023-08-07 21:21 UTC, merged